version: '3.8'

services:
  kafka:
    image: bitnami/kafka:3.7.0
    hostname: kafka
    container_name: kafka
    env_file: .env.cloud
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/bitnami/kafka
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 45s
      timeout: 15s
      retries: 3
      start_period: 90s
    networks:
      - vpbank-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "cloud-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
      LOGGING_LEVEL_ROOT: "WARN"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    restart: unless-stopped
    networks:
      - vpbank-network

  txn-simulator:
    build: .
    container_name: vpbank-txn-simulator
    env_file: .env.cloud
    depends_on:
      kafka:
        condition: service_healthy
      init-kafka:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    restart: unless-stopped
    networks:
      - vpbank-network
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 45s
      timeout: 15s
      retries: 3
      start_period: 60s

  init-kafka:
    image: bitnami/kafka:3.7.0
    depends_on:
      kafka:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
    entrypoint: ['/bin/sh', '-c']
    command: |
      "
      echo 'Waiting for Kafka to be ready...'
      sleep 30
      
      echo 'Creating Kafka topics...'
      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic IBFT --partitions 1 --replication-factor 1 --config retention.ms=3600000
      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic qr_payments --partitions 1 --replication-factor 1 --config retention.ms=3600000
      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic topup_wallet --partitions 1 --replication-factor 1 --config retention.ms=3600000
      
      echo 'Topics created successfully!'
      kafka-topics.sh --bootstrap-server kafka:29092 --list
      "
    networks:
      - vpbank-network

volumes:
  kafka-data:
    driver: local

networks:
  vpbank-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16